version: '3.8'
services:
  mongo-config-server:
    image: mongo:latest
    command: mongod --configsvr --replSet configReplSet --bind_ip_all
    volumes:
      - mongo-configdb:/data/db
    ports:
      - 27019:27019

  mongo-shard1:
    image: mongo:latest
    command: mongod --shardsvr --replSet shard1ReplSet --bind_ip_all
    volumes:
      - mongo-shard1db:/data/db
    ports:
      - 27018:27018

  mongo-router:
    image: mongo:latest
    command: mongos --configdb configReplSet/mongo-config-server:27019 --bind_ip_all
    depends_on:
      - mongo-config-server
      - mongo-shard1
    ports:
      - 4000:27017

volumes:
  mongo-configdb:
  mongo-shard1db:
